[package]
name = "rusaint"
version = "0.1.2"
description = "Easy-to-use SSU u-saint client"
keywords = ["ssu", "u-saint", "scraping", "parser"]
categories = ["web-programming"]
authors = ["Hyomin Koo <me@eatsteak.dev>"]
license = "MIT"
repository = "https://github.com/EATSTEAK/rusaint"
edition = "2021"

[features]
default = ["application", "model"]
application = []
model = ["application"]

[dependencies]
derive_builder = "0.12.0"
reqwest = { version = "0.11.18", features = [
    "cookies",
    "gzip",
    "brotli",
    "deflate",
] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["macros", "test-util"] }
html-escape = "0.2.13"
url = "2.4.1"
roxmltree = "0.18.0"
lol_html = "1.1.1"
scraper = "0.17.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.9.5"
getset = "0.1.2"
custom_debug_derive = "0.5.1"


[dev-dependencies]
anyhow = "1.0.75"
dotenv = "0.15.0"
futures = "0.3.28"
serial_test = "2.0.0"
