[package]
name = "rusaint"
version = "0.1.0"
authors = ["Hyomin Koo <me@eatsteak.dev>"]
license = "MIT"
repository = "https://github.com/EATSTEAK/rusaint"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
reqwest = { version = "0.11.18", features = ["cookies", "gzip", "brotli", "json", "multipart"] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"] }
indexmap = "2.0.0"
html-escape = "0.2.13"
url = "2.4.1"
roxmltree = "0.18.0"
lol_html = "1.1.1"
scraper = "0.17.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
