[package]
name = "rusaint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
reqwest = { version = "0.11.18", features = ["cookies", "gzip", "brotli", "json", "multipart"] }
thiserror = "1.0.44"
tl = "0.7.7"
tokio = { version = "1.29.1", features = ["full"] }
