name: Dry-run before publish

on:
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Retrieve cache
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          cache-key: "dry-run-${{ hashFiles('**/Cargo.lock') }}"
      - name: Publish dry-run
        run: cargo publish -p rusaint --dry-run --verbose
      - name: Run tests
        run: cargo test --verbose
