name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "dev" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    env:
      SSO_ID: ${{ vars.SSO_ID }}
      SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}
      TARGET_YEAR: ${{ vars.TARGET_YEAR }}
      TARGET_SEMESTER: ${{ vars.TARGET_SEMESTER }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Retrieve cache
        uses: Leafwing-Studios/cargo-cache@v2
      - name: Check rustfmt
        run: cargo +nightly fmt
      - name: Check clippy
        run: cargo +nightly clippy -- -D warnings
